### ISSUE TITLE
Bug? Soulbound through enchant 

### ISSUE THREAD

**Issue by madtomic** [TfT-02/Soulbound#38]
![soulbound](https://cloud.githubusercontent.com/assets/6004542/6305839/17e76c62-b8fc-11e4-908d-1e97cc917ff4.png)

Tested on spigot 1.8 using enchanting table.

I tried using the latest build from http://ci.md-5.net/job/Soulbound/lastSuccessfulBuild/

and also download the latest commit source from here and build a fresh jar with marven.

I went in game both times and enchant a sword and it don't have Bind on Use.

I thought it was added so it would also triggers when enchanting.

Can you please take a look at it and see if something was missing?

Thank you,

**Comment by TfT-02** [comment]
Can you post your config files?

**Comment by madtomic** [comment]
http://pastebin.com/WZA36C3N

**Comment by madtomic** [comment]
Pretty much default settings.

**Comment by madtomic** [comment]
I went in creative mode.
Enchanted a shovel and it's bind on use.
Then I issued /bindonuse, which works.
Then I try to use the shovel and this error comes up.

http://pastebin.com/FtDW3UXN

**Comment by madtomic** [comment]
![soulbound2](https://cloud.githubusercontent.com/assets/6004542/6463919/7e43d46a-c184-11e4-9333-470284978153.png)

**Comment by madtomic** [comment]
As you can see. sigh... I would love to get both plugin working together.

**Comment by madtomic** [comment]
I finally found my user error with the issue with the help of a fellow minecrafter! Thanks TheWarezMaster
